name = "jumper-relay"
main = "src/index.ts"
compatibility_date = "2025-01-01"
workers_dev = true

[[routes]]
pattern = "relay.jumper.sh"
custom_domain = true

[[durable_objects.bindings]]
name = "RELAY_SESSION"
class_name = "RelaySession"

[[kv_namespaces]]
binding = "CODES"
id = "99584648ea7d429ab9089633b60de762"

[[migrations]]
tag = "init"
new_classes = ["RelaySession"]
